-- Step 1: Create database and schema for Snowflake Intelligence configuration
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.CONFIGS;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENT_RESOURCES;

-- Step 2: Create stage to hold semantic model YAML files
CREATE STAGE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.CONFIGS.SEMANTIC_MODELS
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Stage for storing semantic model YAML files for Cortex Analyst';

-- Step 3: Upload semantic model files to the stage either via Snowsight UI or via commandline using PUT command


-- Step 4: Grant necessary permissions to read SNOWFLAKE.ACCOUNT_USAGE views
grant database role SNOWFLAKE.OBJECT_VIEWER to role SNOWFLAKE_INTELLIGENCE_ADMIN;
grant database role SNOWFLAKE.USAGE_VIEWER to role SNOWFLAKE_INTELLIGENCE_ADMIN;
grant database role SNOWFLAKE.GOVERNANCE_VIEWER to role SNOWFLAKE_INTELLIGENCE_ADMIN;
grant database role SNOWFLAKE.SECURITY_VIEWER to role SNOWFLAKE_INTELLIGENCE_ADMIN;

--Create the ACCESS_HISTORY_FLATTENED view required by query_analytics.yaml
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.AGENT_RESOURCES.ACCESS_HISTORY_FLATTENED AS
SELECT 
  ah.QUERY_ID,
  ah.PARENT_QUERY_ID,
  ah.ROOT_QUERY_ID,
  ah.USER_NAME,
  ah.QUERY_START_TIME,
  
  -- DIRECT_OBJECTS_ACCESSED
  CAST(GET_PATH(direct_obj.value, 'objectDomain') AS VARCHAR) AS DIRECT_OBJECT_DOMAIN,
  CAST(GET_PATH(direct_obj.value, 'objectName') AS VARCHAR) AS DIRECT_OBJECT_NAME,
  CAST(GET_PATH(direct_obj.value, 'objectId') AS NUMBER) AS DIRECT_OBJECT_ID,
  CAST(GET_PATH(direct_obj.value, 'argumentSignature') AS VARCHAR) AS DIRECT_OBJECT_ARGUMENT_SIGNATURE,
  CAST(GET_PATH(direct_obj.value, 'dataType') AS VARCHAR) AS DIRECT_OBJECT_DATA_TYPE,
  CAST(GET_PATH(direct_col.value, 'columnId') AS NUMBER) AS DIRECT_COLUMN_ID,
  CAST(GET_PATH(direct_col.value, 'columnName') AS VARCHAR) AS DIRECT_COLUMN_NAME,
  -- BASE_OBJECTS_ACCESSED
  CAST(GET_PATH(base_obj.value, 'objectDomain') AS VARCHAR) AS BASE_OBJECT_DOMAIN,
  CAST(GET_PATH(base_obj.value, 'objectName') AS VARCHAR) AS BASE_OBJECT_NAME,
  CAST(GET_PATH(base_obj.value, 'objectId') AS NUMBER) AS BASE_OBJECT_ID,
  CAST(GET_PATH(base_col.value, 'columnId') AS NUMBER) AS BASE_COLUMN_ID,
  CAST(GET_PATH(base_col.value, 'columnName') AS VARCHAR) AS BASE_COLUMN_NAME,
  -- OBJECTS_MODIFIED
  CAST(GET_PATH(mod_obj.value, 'objectDomain') AS VARCHAR) AS MODIFIED_OBJECT_DOMAIN,
  CAST(GET_PATH(mod_obj.value, 'objectName') AS VARCHAR) AS MODIFIED_OBJECT_NAME,
  CAST(GET_PATH(mod_obj.value, 'objectId') AS NUMBER) AS MODIFIED_OBJECT_ID,
  CAST(GET_PATH(mod_col.value, 'columnId') AS NUMBER) AS MODIFIED_COLUMN_ID,
  CAST(GET_PATH(mod_col.value, 'columnName') AS VARCHAR) AS MODIFIED_COLUMN_NAME,
  -- OBJECT_MODIFIED_BY_DDL
  CAST(GET_PATH(ah.OBJECT_MODIFIED_BY_DDL, 'objectDomain') AS VARCHAR) AS DDL_OBJECT_DOMAIN,
  CAST(GET_PATH(ah.OBJECT_MODIFIED_BY_DDL, 'objectName') AS VARCHAR) AS DDL_OBJECT_NAME,
  CAST(GET_PATH(ah.OBJECT_MODIFIED_BY_DDL, 'objectId') AS NUMBER) AS DDL_OBJECT_ID,
  CAST(GET_PATH(ah.OBJECT_MODIFIED_BY_DDL, 'operation') AS VARCHAR) AS DDL_OPERATION,
  -- POLICIES_REFERENCED
  CAST(GET_PATH(policy.value, 'policyName') AS VARCHAR) AS POLICY_NAME,
  CAST(GET_PATH(policy.value, 'policyType') AS VARCHAR) AS POLICY_TYPE,
  CAST(GET_PATH(policy.value, 'policyId') AS NUMBER) AS POLICY_ID,
  
  -- Add flags to identify which type of access this row represents
  CASE WHEN direct_obj.value IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_DIRECT_OBJECT,
  CASE WHEN base_obj.value IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_BASE_OBJECT,
  CASE WHEN mod_obj.value IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_MODIFIED_OBJECT,
  CASE WHEN ah.OBJECT_MODIFIED_BY_DDL IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_DDL_OBJECT,
  CASE WHEN policy.value IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_POLICY_REFERENCE

FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah
LEFT JOIN LATERAL FLATTEN(ah.DIRECT_OBJECTS_ACCESSED) AS direct_obj
LEFT JOIN LATERAL FLATTEN(GET_PATH(direct_obj.value, 'columns'), OUTER => TRUE) AS direct_col
LEFT JOIN LATERAL FLATTEN(ah.BASE_OBJECTS_ACCESSED, OUTER => TRUE) AS base_obj
LEFT JOIN LATERAL FLATTEN(GET_PATH(base_obj.value, 'columns'), OUTER => TRUE) AS base_col
LEFT JOIN LATERAL FLATTEN(ah.OBJECTS_MODIFIED, OUTER => TRUE) AS mod_obj
LEFT JOIN LATERAL FLATTEN(GET_PATH(mod_obj.value, 'columns'), OUTER => TRUE) AS mod_col
LEFT JOIN LATERAL FLATTEN(ah.POLICIES_REFERENCED, OUTER => TRUE) AS policy
WHERE (
  GET_PATH(direct_obj.value, 'objectName') IS NOT NULL OR
  GET_PATH(base_obj.value, 'objectName') IS NOT NULL OR
  GET_PATH(mod_obj.value, 'objectName') IS NOT NULL OR
  ah.OBJECT_MODIFIED_BY_DDL IS NOT NULL OR
  GET_PATH(policy.value, 'policyName') IS NOT NULL
);